export {default as Header} from './header';
export {default as Banner} from './banner';
export {default as Partner} from './partner';
export {default as About} from './about';
export {default as Footer} from './footer';
export {default as WhatWeOffer} from './what-we-offer';
export {default as Projects} from './projects';
export {default as Contectus} from './contectus';
export {default as Data_Protection} from './data-protection';
